namespace Translate;

public class GameTextFiles
{
    // "。" doesnt work like u think it would   
    public static string[] SplitCharactersList = [":", "<br>", "\\n", "-", "|"];

    public static string[] FilesNotHandled = [
        //"ai_dialog.txt",
        "keywordfilter.txt",
        "custom_data.txt",
        "born_points.txt",
        "emoji.txt",
        "dlc_prototype.txt",
        "dlc_prototype_mobile.txt",
        "dlc_data.txt",
    ];

    public static readonly TextFileToSplit[] TextFilesToSplit = [
        // Invalid for translation        
        //new() {Path = "keywordfilter.txt"},
        //new() {Path = "custom_data.txt", Output = true, OutputRawResource = true},
        //new() {Path = "born_points.txt", Output = true},
        //new() {Path = "emoji.txt", PackageOutput = true},
        //new() {Path = "dlc_prototype.txt", PackageOutput = true },
        //new() {Path = "dlc_prototype_mobile.txt", PackageOutput = true },
        //new() {Path = "dlc_data.txt", PackageOutput = true },

        new() {Path = "ai_dialog.txt", PackageOutput = true},
        new() {Path = "local_text_string.txt", PackageOutput = true, TextFileType = TextFileType.LocalTextString },
        new() {Path = "dlcinfo.txt", PackageOutput = true },
        
        new() {Path = "achievement.txt", PackageOutput = true},
        new() {Path = "achievement_xianejianghu.txt", PackageOutput = true},
        new() {Path = "achievement_zhenshijianghu.txt", PackageOutput = true},
        new() {Path = "buildprototype.txt", PackageOutput = true},
        new() {Path = "cardinfo.txt", PackageOutput = true},
        new() {Path = "chuanwenprototype.txt", PackageOutput = true},
        new() {Path = "condition_group.txt", PackageOutput = true},
        new() {Path = "condition_group_dangmojianghu.txt", PackageOutput = true},
        new() {Path = "condition_show_anim.txt", PackageOutput = true},
        new() {Path = "dumpedPrefabText.txt", TextFileType = TextFileType.PrefabText, AllowMissingColorTags = false},
        new() {Path = "dynamicStrings.txt", TextFileType = TextFileType.DynamicStrings, AllowMissingColorTags = false},
        new() {Path = "entrust_event_prototype.txt", PackageOutput = true},
        new() {Path = "fuben_prototype.txt", PackageOutput = true},
        new() {Path = "game_manual.txt", PackageOutput = true},
        new() {Path = "game_manual_clue.txt", PackageOutput = true},
        new() {Path = "guanqiaenemy.txt", PackageOutput = true},
        new() {Path = "guanqiainfo.txt", PackageOutput = true},
        new() {Path = "horoscope.txt", PackageOutput = true, AdditionalPromptName = "FileHoroscopePrompt"},
        new() {Path = "identity.txt", PackageOutput = true},
        new() {Path = "item_base.txt", PackageOutput = true},
        new() {Path = "item_base_dangmojianghu.txt", PackageOutput = true},
        new() {Path = "item_base_xianejianghu.txt", PackageOutput = true},
        new() {Path = "item_base_zhenshijianghu.txt", PackageOutput = true},
        new() {Path = "item_ma_prototype.txt", PackageOutput = true},
        new() {Path = "jingmai_node_pos.txt", PackageOutput = true},
        new() {Path = "jueyinglou.txt", PackageOutput = true},
        new() {Path = "keylist.txt", PackageOutput = true},
        new() {Path = "loadingpicture.txt", PackageOutput = true},
        new() {Path = "loadingtips.txt", PackageOutput = true},
        
        new() {Path = "living_assemblyskill.txt", PackageOutput = true },
        new() {Path = "living_assemblyskill_zhenshijianghu.txt", PackageOutput = true },
        new() {Path = "makerplayer_prototype.txt", PackageOutput = true},
        new() {Path = "mapinfo.txt", PackageOutput = true},
        new() {Path = "map_area.txt", PackageOutput = true},
        new() {Path = "map_area_shili.txt", PackageOutput = true},
        new() {Path = "map_area_title.txt", PackageOutput = true},
        new() {Path = "menpai.txt", PackageOutput = true},
        new() {Path = "menpaibuild.txt", PackageOutput = true},
        new() {Path = "menpaipaibie.txt", PackageOutput = true},
        new() {Path = "menpaipeifang.txt", PackageOutput = true},
        new() {Path = "menpaiquest.txt", PackageOutput = true},
        new() {Path = "menpairandom.txt", PackageOutput = true},
        new() {Path = "menpaisoldier.txt", PackageOutput = true},
        new() {Path = "menpaitalent.txt", PackageOutput = true},
        new() {Path = "mystique.txt", PackageOutput = true},
        new() {Path = "nandu.txt", PackageOutput = true},
        new() {Path = "npc_interact.txt", PackageOutput = true},
        new() {Path = "npc_interact_dangmojianghu.txt", PackageOutput = true},
        new() {Path = "npc_prototype.txt", PackageOutput = true},
        new() {Path = "npc_prototype_dangmojianghu.txt", PackageOutput = true},
        new() {Path = "npc_spell_container.txt", PackageOutput = true},
        new() {Path = "npc_spell_dynamic_name.txt", PackageOutput = true},
        new() {Path = "npc_team_info.txt", PackageOutput = true},
        new() {Path = "pve_data.txt", PackageOutput = true},
        new() {Path = "qinggong_node.txt", PackageOutput = true},
        new() {Path = "questjiemi.txt", PackageOutput = true},
        new() {Path = "questprototype.txt", PackageOutput = true },
        new() {Path = "randomname.txt", PackageOutput = true, AdditionalPromptName = "FileRandomNamePrompt",
            EnableGlossary = false, EnableBasePrompts = false, RemoveNumbers = true, NameCleanupRoutines = true},
        new() {Path = "randomnamenew.txt", PackageOutput = true, AdditionalPromptName = "FileRandomNameNewPrompt",
            EnableGlossary = false, EnableBasePrompts = false, RemoveNumbers = true, NameCleanupRoutines2 = true},
        new() {Path = "randomquestion.txt", PackageOutput = true},
        new() {Path = "shangcheng_prototype.txt", PackageOutput = true},
        new() {Path = "spelleffect.txt", PackageOutput = true},
        new() {Path = "spelleffect_dangmojianghu.txt", PackageOutput = true},
        new() {Path = "spelleffect_xianejianghu.txt", PackageOutput = true},
        new() {Path = "spelleffect_zhenshijianghu.txt", PackageOutput = true},
        new() {Path = "spellprotype.txt", PackageOutput = true},
        new() {Path = "spellprotype_dangmojianghu.txt", PackageOutput = true},
        new() {Path = "spellprotype_xianejianghu.txt", PackageOutput = true},
        new() {Path = "spellprotype_zhenshijianghu.txt", PackageOutput = true},
        new() {Path = "stunt_proto.txt", PackageOutput = true},
        new() {Path = "system_introduce.txt", PackageOutput = true},
        new() {Path = "talent_proto.txt", PackageOutput = true},
        new() {Path = "teleport_trans.txt", PackageOutput = true},
        new() {Path = "triggertip.txt", PackageOutput = true},
        new() {Path = "tujian.txt", PackageOutput = true},
        new() {Path = "wordentryrandomtype.txt", PackageOutput = true},
        new() {Path = "wordentrytitle.txt", PackageOutput = true},
        new() {Path = "wordentrytype.txt", PackageOutput = true},
        new() {Path = "xunwen_prototype.txt", PackageOutput = true},
        new() {Path = "yingdao_prototype.txt", PackageOutput = true},

        //Biggest one
        new() {Path = "stringlang.txt", PackageOutput = true, IsMainDialogueAsset = true, }, //RemoveExtraFullStop = false
    ];
}
